services:
  mongodb:
    image: mongo:8.0.14-rc0
    container_name : mongodb
    
    ports:
      - "7412:27017"
    
    volumes:
      - "mongodata:/data/db"
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - backend
    
    restart : always

networks:
  backend:

volumes:
  mongodata: